"""Initial schema

Revision ID: 6baed0fbaebe
Revises:
Create Date: 2025-04-11 19:59:38.263019

"""

# revision identifiers, used by Alembic.
revision = "6baed0fbaebe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
