"""Rename news table to posts

Revision ID: cdf5af70cf95
Revises: d373f6f8fba9
Create Date: 2025-04-11 21:09:05.832239

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdf5af70cf95"
down_revision = "d373f6f8fba9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_news_id", table_name="news")
    op.drop_index("ix_news_post_id", table_name="news")
    op.drop_table("news")
    op.drop_column("posts", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("content", sa.VARCHAR(), nullable=False))
    op.create_table(
        "news",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("content", sa.VARCHAR(), nullable=False),
        sa.Column("source", sa.VARCHAR(), nullable=True),
        sa.Column("published_at", sa.DATETIME(), nullable=True),
        sa.Column("post_id", sa.VARCHAR(), nullable=True),
        sa.Column("text", sa.VARCHAR(), nullable=True),
        sa.Column("author", sa.VARCHAR(), nullable=True),
        sa.Column("upvotes", sa.INTEGER(), nullable=True),
        sa.Column("url", sa.VARCHAR(), nullable=True),
        sa.Column("published_date", sa.VARCHAR(), nullable=True),
        sa.Column("comment_url", sa.VARCHAR(), nullable=True),
        sa.Column("sub", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_news_post_id", "news", ["post_id"], unique=False)
    op.create_index("ix_news_id", "news", ["id"], unique=False)
    # ### end Alembic commands ###
