"""Initial schema

Revision ID: f01dcbc87140
Revises: f143c6a69210
Create Date: 2025-04-11 20:03:42.490547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01dcbc87140'
down_revision = 'f143c6a69210'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
