"""Initial schema

Revision ID: f143c6a69210
Revises: 6baed0fbaebe
Create Date: 2025-04-11 19:59:52.370402

"""

# revision identifiers, used by Alembic.
revision = "f143c6a69210"
down_revision = "6baed0fbaebe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
