{
    "kind": "t3",
    "data": {
        "approved_at_utc": None,
        "subreddit": "reactjs",
        "selftext": "I've been using React for a little more than 2 years and more recently everything sort of started to \"come together.\" In the beginning I was using effects incorrectly and didn't have a full understanding of how refs worked. These 2 documents were game changing:\n\n[https: //react.dev/learn/you-might-not-need-an-effect](https://react.dev/learn/you-might-not-need-an-effect)\n\n[https://react.dev/learn/referencing-values-with-refs](https://react.dev/learn/referencing-values-with-refs)  \n  \nHonestly, after grasping these things, the draw to something like svelte or other frameworks just sort of loses its appeal. I think react has a steeper learning curve, but once you get past it there's really nothing *wrong* per se with React and it's actually a very enjoyable experience.",
        "author_fullname": "t2_66cks94",
        "saved": False,
        "mod_reason_title": None,
        "gilded": 0,
        "clicked": False,
        "title": "React is fantastic once things click",
        "link_flair_richtext": [],
        "subreddit_name_prefixed": "r/reactjs",
        "hidden": False,
        "pwls": 6,
        "link_flair_css_class": "link-flair-discussion",
        "downs": 0,
        "thumbnail_height": None,
        "top_awarded_type": None,
        "hide_score": False,
        "name": "t3_1jpn7zv",
        "quarantine": False,
        "link_flair_text_color": None,
        "upvote_ratio": 0.94,
        "author_flair_background_color": None,
        "subreddit_type": "public",
        "ups": 202,
        "total_awards_received": 0,
        "media_embed": {},
        "thumbnail_width": None,
        "author_flair_template_id": None,
        "is_original_content": False,
        "user_reports": [],
        "secure_media": None,
        "is_reddit_media_domain": False,
        "is_meta": False,
        "category": None,
        "secure_media_embed": {},
        "link_flair_text": "Discussion",
        "can_mod_post": False,
        "score": 202,
        "approved_by": None,
        "is_created_from_ads_ui": False,
        "author_premium": False,
        "thumbnail": "self",
        "edited": False,
        "author_flair_css_class": None,
        "author_flair_richtext": [],
        "gildings": {},
        "post_hint": "self",
        "content_categories": None,
        "is_self": True,
        "mod_note": None,
        "created": 1743596529.0,
        "link_flair_type": "text",
        "wls": 6,
        "removed_by_category": None,
        "banned_by": None,
        "author_flair_type": "text",
        "domain": "self.reactjs",
        "allow_live_comments": False,
        "selftext_html": '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I&amp;#39;ve been using React for a little more than 2 years and more recently everything sort of started to &amp;quot;come together.&amp;quot; In the beginning I was using effects incorrectly and didn&amp;#39;t have a full understanding of how refs worked. These 2 documents were game changing:&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://react.dev/learn/you-might-not-need-an-effect"&gt;https://react.dev/learn/you-might-not-need-an-effect&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://react.dev/learn/referencing-values-with-refs"&gt;https://react.dev/learn/referencing-values-with-refs&lt;/a&gt;  &lt;/p&gt;\n\n&lt;p&gt;Honestly, after grasping these things, the draw to something like svelte or other frameworks just sort of loses its appeal. I think react has a steeper learning curve, but once you get past it there&amp;#39;s really nothing &lt;em&gt;wrong&lt;/em&gt; per se with React and it&amp;#39;s actually a very enjoyable experience.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
        "likes": None,
        "suggested_sort": "confidence",
        "banned_at_utc": None,
        "view_count": None,
        "archived": False,
        "no_follow": False,
        "is_crosspostable": False,
        "pinned": False,
        "over_18": False,
        "preview": {
            "images": [
                {
                    "source": {
                        "url": "https://external-preview.redd.it/wSnWx186Dd3XC93p4zhHVbmLgGW-4tKFrcGHyu3RSZM.jpg?auto=webp&amp;s=fb9efb9de2ec8effdc6dcb116858b350488f0972",
                        "width": 1080,
                        "height": 567,
                    },
                    "resolutions": [
                        {
                            "url": "https://external-preview.redd.it/wSnWx186Dd3XC93p4zhHVbmLgGW-4tKFrcGHyu3RSZM.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=f03a35c2649e1b2f8103fe511d54120989c63570",
                            "width": 108,
                            "height": 56,
                        },
                        {
                            "url": "https://external-preview.redd.it/wSnWx186Dd3XC93p4zhHVbmLgGW-4tKFrcGHyu3RSZM.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=9b3da4812794464a02c0e72dd4b72ebae409debd",
                            "width": 216,
                            "height": 113,
                        },
                        {
                            "url": "https://external-preview.redd.it/wSnWx186Dd3XC93p4zhHVbmLgGW-4tKFrcGHyu3RSZM.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=a3e022b1f6f7dacfa617bc57c5d7186678de7f9d",
                            "width": 320,
                            "height": 168,
                        },
                        {
                            "url": "https://external-preview.redd.it/wSnWx186Dd3XC93p4zhHVbmLgGW-4tKFrcGHyu3RSZM.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=ec8f71fbf17e8d6e61d36b387f032bd4e5fc2afb",
                            "width": 640,
                            "height": 336,
                        },
                        {
                            "url": "https://external-preview.redd.it/wSnWx186Dd3XC93p4zhHVbmLgGW-4tKFrcGHyu3RSZM.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=5bd3b7615da3fbc84bc68a87eaa8021d770ba44a",
                            "width": 960,
                            "height": 504,
                        },
                        {
                            "url": "https://external-preview.redd.it/wSnWx186Dd3XC93p4zhHVbmLgGW-4tKFrcGHyu3RSZM.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=b40130219339e71f564fa3c13656e287e518b183",
                            "width": 1080,
                            "height": 567,
                        },
                    ],
                    "variants": {},
                    "id": "k8Y6E6yEvPA8HTo69HA6FEct0aHEHHr758AwMitTOTQ",
                }
            ],
            "enabled": False,
        },
        "all_awardings": [],
        "awarders": [],
        "media_only": False,
        "link_flair_template_id": "01a7aefe-4b81-11ea-bbb7-0e04580e4d4d",
        "can_gild": False,
        "spoiler": False,
        "locked": False,
        "author_flair_text": None,
        "treatment_tags": [],
        "visited": False,
        "removed_by": None,
        "num_reports": None,
        "distinguished": None,
        "subreddit_id": "t5_2zldd",
        "author_is_blocked": False,
        "mod_reason_by": None,
        "removal_reason": None,
        "link_flair_background_color": "#73ad34",
        "id": "1jpn7zv",
        "is_robot_indexable": True,
        "report_reasons": None,
        "author": "blabmight",
        "discussion_type": None,
        "num_comments": 55,
        "send_replies": True,
        "contest_mode": False,
        "mod_reports": [],
        "author_patreon_flair": False,
        "author_flair_text_color": None,
        "permalink": "/r/reactjs/comments/1jpn7zv/react_is_fantastic_once_things_click/",
        "stickied": False,
        "url": "https://www.reddit.com/r/reactjs/comments/1jpn7zv/react_is_fantastic_once_things_click/",
        "subreddit_subscribers": 453456,
        "created_utc": 1743596529.0,
        "num_crossposts": 0,
        "media": None,
        "is_video": False,
    },
}
